### ISSUE TITLE
老哥，为什么我运行后一堆报错？

### ISSUE THREAD

**Issue by lyz0313** [liangzelang/OpenTLD_OpenCV3#1]
![image](https://user-images.githubusercontent.com/43334762/67481966-9435d400-f66b-11e9-9139-4d9602906f0a.png)

主要就是说这个值c没有定义。但是我看代码前边定义了c，不知道编译器为何识别不了

**Comment by liangzelang** [comment]
这个定义了的  我这边是没有任何问题的
你看一下 你是不是自己编译什么有问题
